--- 
title: "R程式語言自我筆記(基礎篇)"
author: "Lucy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

## 關於作者

跨領域的我，早年是在醫院及大學從事研究助理，協助教授或醫師收集臨床試驗的病人，在漫長工作生涯中，發現收集臨床資料，進行統計分析，是個人最喜歡的工作項目。早年學校習得高等統計知識及SPSS軟體應用後，到自己出社會以後自學R，在資料分析的路上越走越遠，但仍感謝過去工作實務經驗讓自己即使跨領域，轉行投入氣象數據分析，也不至於讓自己窘迫。

## 本書的定位

網路上其實很多免費的線上R教學，基礎教學偏多，而稍複雜一點Code常常散落各地，雖然自身有用Nation隨時進行筆記摘錄，但是隨著筆記越來越多時，便有了想統整一份專屬自己學習後的內化筆記，而當這想法開始縈繞在我心中時，便有了開始撰寫這本線上電子書念頭。本書定位為起始筆記第一個敲門磚，未來會逐步加強充實內容，預計會寫下列幾個系列筆記，第一部分**R程式語言(基礎、中階及高階)**，不太涉及統計原理方面知識，而是單純介紹R程式語言，此部分算是R的最基本功，往往運用在資料前處理時各種資料轉換，第二部分 **統計學與R操作**，側重在統計學觀念的釐清及如何應用R來進行統計分析，此部分教學，會與SPSS進行搭配輔助說明，其目的是讓有一定統計知識且慣用SPSS的統計人員，能利用過去分析經驗來銜接，輔助有心轉換分析跑道的學者能快速使用R來進行統計。**第三部分 介紹時下最流行大數據工具**，第四部份重點在於**精進R分析者工作技能**，例如用R來 收信及寄信，用R串聯google文件、google活頁簿及如何用R進行網路爬蟲蒐集資料。

1.  R程式語言
    -   基礎R程式
    -   中階R程式
    -   高階R程式
2.  統計學與R操作
    -   描述性統計
    -   推論性統計
3.  大數據分析與R
    -   非監督式學習
    -   監督式學習
4.  R及RStudio專章性學習
    -   RStudio與git、GitHub 互動
    -   R程式與文書處理
    -   網路爬蟲與R程式

## 參考資料

### 線上中文資源

-   [曾意儒 --資料科學與R語言](https://yijutseng.github.io/DataScienceRBook/)
-   [郭耀仁 --認識R的美好](https://bookdown.org/tonykuoyj/eloquentr/)
-   [林建甫 --R資料科學與統計](https://bookdown.org/jefflinmd38/r4biost/)

### 中文書籍


